version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run: npm i
      - run: npm build
  test:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run: npm i
      - run: npm test
workflows:
  version: 2.1
  build-test:
    jobs:
      - build
      - test
