version: 2.1
jobs:
  build:
    - image: circleci/node:8.9
  steps:
    - checkout
    - run: yarn
    - run: yarn build
  test:
    - image: circleci/node:8.9
  steps:
    - checkout
    - run: yarn
    - run: yarn test
workflows:
  version: 2.1
  build-test:
    jobs:
      - build
      - test