version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2.1
  build-test:
    jobs:
      - build
      - test
